#!/usr/bin/env bash
# scripts/grade-snapshot.sh
#
# Grades data/health.json against the same rollup rules the dashboard uses
# (core-aware, shared-host aware). Produces two things:
#
#   1. An alert-body markdown file at $2 (empty when everything's green).
#   2. A one-line JSON summary on stdout:
#        {"hash": "...", "alert_count": N, "subject": "...", "title": "..."}
#      `hash` is a stable hash of (alias, state) pairs across non-green hosts
#      so the workflow can tell "same alert as last time" from "state changed"
#      without comparing rendered markdown.
#
# Usage:
#   ./scripts/grade-snapshot.sh [HEALTH_JSON] [ALERT_MD]
#
# Env vars:
#   ALERT_MENTIONS  space-separated @mentions embedded in the alert body
#                   (default: "@azlangaida @gda-gusde")
#   DASHBOARD_URL   link included in the alert body (defaults to the public
#                   dashboard).

set -euo pipefail

HEALTH_JSON="${1:-data/health.json}"
ALERT_MD="${2:-/tmp/alert.md}"

MENTIONS="${ALERT_MENTIONS:-@azlangaida @gda-gusde}"
DASHBOARD_URL="${DASHBOARD_URL:-https://gaia-digital-agency.github.io/infara_monitor/}"

command -v jq >/dev/null 2>&1 || { echo "grade-snapshot: jq not found" >&2; exit 1; }
[ -r "$HEALTH_JSON" ] || { echo "grade-snapshot: cannot read $HEALTH_JSON" >&2; exit 1; }

# Non-green hosts with per-host reason strings. Keep the jq self-contained so
# the rules live in one place and match the dashboard exactly.
NON_GREEN=$(jq -c '
  [ .hosts[] |
    (if .reachable then
       if .kind == "shared" then
         (if (.disk_used_pct // 0) >= 95 then "red"
          elif (.disk_used_pct // 0) >= 85 then "yellow"
          else "green" end) as $s
         | { alias: .alias, state: $s,
             reasons: ([
               (if (.disk_used_pct // 0) >= 85
                then "disk \(.disk_used_pct // 0)% (host-wide)"
                else empty end)
             ]) }
       else
         (((.load1 // 0) / (.ncpu // 1)) as $lp
          | (if $lp >= 2 or (.mem_used_pct // 0) >= 90 or (.disk_used_pct // 0) >= 95 then "red"
             elif $lp >= 1 or (.mem_used_pct // 0) >= 80 or (.disk_used_pct // 0) >= 85 then "yellow"
             else "green" end) as $s
          | { alias: .alias, state: $s,
              reasons: ([
                (if $lp >= 1
                 then "load1 \(.load1 // 0) on \(.ncpu // 1) core\(if (.ncpu // 1) == 1 then "" else "s" end) (\(($lp * 100) | floor)%/core)"
                 else empty end),
                (if (.mem_used_pct // 0) >= 80
                 then "mem \(.mem_used_pct)% used"
                 else empty end),
                (if (.disk_used_pct // 0) >= 85
                 then "disk \(.disk_used_pct)% used"
                 else empty end)
              ]) })
       end
     else
       { alias: .alias, state: "red",
         reasons: [ "UNREACHABLE: \(.ssh_error // "ssh failed")" ] }
     end)
    | select(.state != "green")
  ]
' "$HEALTH_JSON")

ALERT_COUNT=$(echo "$NON_GREEN" | jq 'length')

# Stable hash of (alias, state) — unchanged => body-only update, no comment.
HASH=$(echo "$NON_GREEN" \
  | jq -r 'map("\(.alias):\(.state)") | sort | .[]' \
  | { sha1sum 2>/dev/null || shasum -a 1; } \
  | awk '{print $1}')

if [ "$ALERT_COUNT" -eq 0 ]; then
  : > "$ALERT_MD"
  jq -nc '{hash: "", alert_count: 0, subject: "", title: ""}'
  exit 0
fi

# Title ingredients.
HOST_LIST=$(echo "$NON_GREEN" | jq -r '[.[].alias] | join(", ")')
STATE_MIX=$(echo "$NON_GREEN" | jq -r '
  [.[].state] | unique
  | if any(. == "red") and any(. == "yellow") then "red + yellow"
    elif any(. == "red") then "red"
    elif any(. == "yellow") then "yellow"
    else "?" end')
SUBJECT="$STATE_MIX on $HOST_LIST"
TITLE="🚨 Health alert — $SUBJECT"

GENERATED_AT=$(jq -r '.generated_at' "$HEALTH_JSON")

# List the hosts that are still green so the operator sees the full picture.
GREEN_HOSTS=$(jq -r '
  [ .hosts[] |
    (if .reachable then
       if .kind == "shared" then
         (if (.disk_used_pct // 0) >= 85 then empty else .alias end)
       else
         (((.load1 // 0) / (.ncpu // 1)) as $lp
          | if $lp >= 1 or (.mem_used_pct // 0) >= 80 or (.disk_used_pct // 0) >= 85
            then empty
            else .alias end)
       end
     else empty end)
  ] | if length == 0 then "(none)" else join(", ") end
' "$HEALTH_JSON")

{
  echo "🚨 **Health alert** — $STATE_MIX"
  echo
  echo "Snapshot \`$GENERATED_AT\` — [open dashboard]($DASHBOARD_URL)"
  echo
  echo "| Host | Status | Reason |"
  echo "|---|---|---|"
  echo "$NON_GREEN" | jq -r '.[] |
    "| `\(.alias)` | \(if .state == "red" then "🔴 red" else "🟡 yellow" end) | \(.reasons | join("; ")) |"'
  echo
  echo "**Green:** $GREEN_HOSTS"
  echo
  echo "cc $MENTIONS"
  echo
  echo "<!-- auto-generated by scripts/grade-snapshot.sh; do not edit below -->"
  echo "<!-- hash:$HASH -->"
  echo "<!-- generated_at:$GENERATED_AT -->"
} > "$ALERT_MD"

jq -nc \
  --arg hash "$HASH" \
  --argjson count "$ALERT_COUNT" \
  --arg subject "$SUBJECT" \
  --arg title "$TITLE" '
    {hash: $hash, alert_count: $count, subject: $subject, title: $title}'
